// components/Header.tsx
import { Box, Flex, Text } from "@chakra-ui/react";

type Props = {
    title: string,
    children: React.ReactNode
}

export default function Header(props: Props) {
    const { title, children } = props;

    return (
        <Flex as="header"
            position="absolute"
            top="0"
            left="0"
            right="0"
            align="center"
            justify="space-between"
            px={6}
            py={4}
            className="animated-header"
        >
            <Text fontSize="xl" fontWeight="semibold">{title}</Text>
            <Box>
                {children}
            </Box>
        </Flex>
    );
}

// components/Header.vue
<template>
    <header class="animated-header">
        <div class="top-left">
            <h1 class="is-size-5 has-text-weight-semibold has-text-dark">Gradient Clock</h1>
        </div>
        <div class="top-right">
            <FullscreenButton />
        </div>
    </header>
</template>

<script>
    import FullscreenButton from '../components/FullscreenButton';

    export default {
        components: { FullscreenButton }
    }
</script>

<style scoped>
    .animated-header {
        opacity: 0;
        position: absolute;
        top: 0;
        right: 0;
        left: 0;
        display: flex;
        align-items: center;
        justify-content: space-between;
        padding: 1rem;
        padding-left: 1.5rem;
        padding-right: 1.5rem;
    }

    div.top-right>:not(:last-child) {
        margin-right: 1rem;
    }

    button, a {
        background-color: transparent;
        border: 0 !important;
    }
</style>
