// pages/index.vue
<template>
    <div id="clock-app">
        <Gradient />
        <HeaderAnimationTarget>
            <section class="hero is-fullheight">
                <div class="hero-body">
                    <Header />
                    <Clock />
                </div>
            </section>
        </HeaderAnimationTarget>
    </div>
</template>

<script>
    import Clock from '../components/Clock';
    import Gradient from '../components/Gradient';
    import HeaderAnimationTarget from '../components/HeaderAnimationTarget';
    import Header from '../components/Header';

    export default {
        components: { Clock, Gradient, HeaderAnimationTarget, Header },

        mounted() {
            console.log('Hey there.');
            console.log('https://github.com/FestiveAkp/clock');
        }
    }
</script>

<style>
    html {
        overflow: hidden !important;
    }
</style>

// pages/index.tsx
import { Flex } from '@chakra-ui/react';
import { useEffect } from 'react';
import Header from '../components/Header';
import FullscreenButton from '../components/FullscreenButton';
import Clock from '../components/Clock';

export default function IndexPage() {
    useEffect(() => {
        console.log('Hey there.');
        console.log('https://github.com/FestiveAkp/clock');
    }, []);

    return (
        <Flex as="main" minHeight="100vh" align="center" justify="center">
            <Header title="Gradient Clock">
                <FullscreenButton />
            </Header>
            <Clock />
        </Flex>
    );
}
